### PR TITLE
update version number for CRAN submission

### PR DESCRIPTION
**Pull request by mariumtapal**

### CODE REVIEW

**Comment by mariumtapal** [comment]
@beanumber submitted to CRAN and got some comments. Have fixed the URL issues. Not sure why the HTML5 note is still appearing because I fixed it earlier and double-checked it -- there is also no file called `fec16.html`.  Any ideas what is going on?

```
Dear maintainer,

package fec16_0.1.4.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
Windows: <https://win-builder.r-project.org/incoming_pretest/fec16_0.1.4_20230716_223325/Windows/00check.log>
Status: 2 NOTEs
Debian: <https://win-builder.r-project.org/incoming_pretest/fec16_0.1.4_20230716_223325/Debian/00check.log>
Status: 2 NOTEs



Please fix all problems and resubmit a fixed version via the webform.
If you are not sure how to fix the problems shown, please ask for help on the R-package-devel mailing list:
<https://stat.ethz.ch/mailman/listinfo/r-package-devel>
If you are fairly certain the rejection is a false positive, please reply-all to this message and explain.

More details are given in the directory:
<https://win-builder.r-project.org/incoming_pretest/fec16_0.1.4_20230716_223325/>
The files will be removed after roughly 7 days.

No strong reverse dependencies to be checked.

Best regards,
CRAN teams' auto-check service
Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-x86_64
Check: CRAN incoming feasibility, Result: NOTE
 Maintainer: 'Marium Tapal <[mariumtapal@gmail.com](mailto:mariumtapal@gmail.com)>'

 New submission

 Package was archived on CRAN

 CRAN repository db overrides:
   X-CRAN-Comment: Archived on 2022-10-03 as check issues were not
     corrected despite reminders.

 Found the following (possibly) invalid URLs:
   URL: https://github.com/hadley/nycflights13 (moved to https://github.com/tidyverse/nycflights13)
     From: inst/doc/fec_vignette.html
     Status: 301
     Message: Moved Permanently
   URL: https://www.tidyverse.org/lifecycle/#maturing (moved to https://lifecycle.r-lib.org/articles/stages.html#maturing)
     From: README.md
     Status: 301
     Message: Moved Permanently

Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-x86_64
Check: HTML version of manual, Result: NOTE
 Found the following HTML validation problems:
 fec16.html:29:4 (fec16.Rd:12): Warning: <img> attribute "align" not allowed for HTML5
 ```

**Comment by beanumber** [comment]
My guess is here: https://github.com/baumer-lab/fec16/blob/5e9ba148ae4297f837e3640f105c59ce954b3337/R/fec16-package.R#L6C1-L6C104

**Comment by mariumtapal** [comment]
@beanumber I think I've fixed the problem -- CRAN team is on vacation till tomorrow. Will try to resubmit after!

**Comment by beanumber** [comment]
Great. Thanks!

**Pull request merged**
